image: node:12

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
  except:
    - master

test:
  stage: test
  script:
    - npm test
  except:
    - master

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mkdir .public
    - cp -r dist/* .public
    - cp dist/index.html .public/404.html
    - mv .public public
  artifacts:
    paths:
    - public
  only:
    - master
