image: node:12

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  
build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
  except:
    - master

test:
  stage: test
  script:
    - npm test
  except:
    - master
