export const userConstants = {
    REGISTER_IDLE: 'REGISTER_IDLE',
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    ACCOUNT_CONFIRMATION_SUCCESS: "ACCOUNT_CONFIRMATION_SUCCESS",
    ACCOUNT_CONFIRMATION_FAILURE: "ACCOUNT_CONFIRMATION_FAILURE",

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
};