export const fieldTypes = {
    email: (t: any) => ({
        id: 'email',
        name: 'email',
        type: 'email',
        label: t('EMAIL'),
        placeholder: t('ENTER_EMAIL_INPUT_PLACEHOLDER'),
        required: true,
        autoComplete: 'on',
    }),
    new_email: (t: any) => ({
        id: 'new_email',
        name: 'email',
        type: 'email',
        label: t('NEW_EMAIL_ADDRESS'),
        placeholder: t('NEW_EMAIL_ADDRESS_ENTER'),
        required: true,
        autoComplete: 'on',
    }),
    new_username: (t: any) => ({
        id: 'new_username',
        name: 'new_username',
        type: 'text',
        label: t('NEW_USERNAME'),
        placeholder: t('ENTER_NEW_USERNAME_INPUT_PLACEHOLDER'),
        required: true,
        autoComplete: 'on',
    }),
    username: (t: any) => ({
        id: 'username',
        name: 'username',
        type: 'text',
        label: t('USERNAME'),
        placeholder: t('ENTER_USERNAME_INPUT_PLACEHOLDER'),
        required: true,
        autoComplete: 'on',
    }),
    password: (t: any) => ({
        id: 'password',
        name: 'password',
        type: 'password',
        label: t('PASSWORD'),
        placeholder: t('ENTER_PASSWORD'),
        required: true,
        autoComplete: 'on',
    }),
    current_password: (t: any) => ({
        id: 'current_password',
        name: 'current_password',
        type: 'password',
        label: t('CURRENT_PASSWORD'),
        placeholder: t('CURRENT_PASSWORD_ENTER'),
        required: true,
        autoComplete: 'on',
    }),
    new_password: (t: any) => ({
        id: 'new_password',
        name: 'new_password',
        type: 'password',
        label: t('NEW_PASSWORD'),
        placeholder: t('NEW_PASSWORD_ENTER'),
        required: true,
        autoComplete: 'on',
    }),
    new_password_confirm: (t: any) => ({
        id: 'new_password_confirm',
        name: 'new_password_confirm',
        type: 'password',
        label: t('NEW_PASSWORD_CONFIRM'),
        placeholder: t('INPUT_PASSWORD_CONFIRM_PLACEHOLDER'),
        required: true,
        autoComplete: 'on',
    }),
};